#!perl
use v5.42;

use Cpanel::JSON::XS (); # force to use Cpanel::JSON::XS to generate META.json
use Dist::Zilla::App;
use Mojo::File;
use Mojo::Loader;
use Software::License::Perl_5;

package Template {
    use Mojo::Base -base, -signatures;

    use Mojo::File;
    use Mojo::Template;

    has argv => undef;
    has data => undef;
    has tmpl => sub ($self, @) { Mojo::Template->new(vars => 1) };

    sub render ($self, $source, $target) {
        my $file = Mojo::File->new($target);
        $file->dirname->make_path if !-d $file->dirname;
        $file->spew($self->tmpl->render($self->data->{$source}, $self->argv));
    }
}

my sub capture (@cmd) { qx/@cmd/ =~ s/\n\z//r }

die "Usage: $0 MODULE\n" if !@ARGV or $ARGV[0] =~ /^(-h|--help)$/n;

my $module = $ARGV[0] =~ s/(::|-)/::/gr;
my $dist = $module =~ s/::/-/gr;
my $author = capture qw(git config --get user.name);
my $email = capture qw(git config --get user.email);
my $github_user = capture qw(git config --get github.user) or die "missing 'git config --get github.user'\n";
my $year = (localtime)[5] + 1900;

my $tmpl = Template->new(
    argv => { module => $module, dist => $dist, author => $author, email => $email, year => $year },
    data => (Mojo::Loader::data_section __PACKAGE__),
);
my $license = Software::License::Perl_5->new({ holder => "$author <$email>", year => $year });

my $dir = Mojo::File->new("perl-$dist");
die "Already exist $dir\n" if -e $dir;

warn "Creating ./$dir\n";
$dir->make_path;

my @part = split /-/, $dist;
my $last = pop @part;
my $libfile = Mojo::File->new("lib", @part, "$last.pm");

chdir $dir;

$tmpl->render("Module.pm" => $libfile);
$tmpl->render(".github/workflows/ci.yml" => ".github/workflows/ci.yml");
$tmpl->render(".gitignore" => ".gitignore");
$tmpl->render(".gitattributes" => ".gitattributes");
$tmpl->render("Changes" => "Changes");
$tmpl->render("Build.PL" => "Build.PL");
$tmpl->render("dist.pl" => "dist.pl");
$tmpl->render("t/00_use.t" => "t/00_use.t");
Mojo::File->new("LICENSE")->spew($license->fulltext);

system "git", "init", "-q", ".";
system "git", "add", ".";
system "git", "remote", "add", "origin", "ssh://git\@github.com/$github_user/perl-$dist.git";
{ local @ARGV = ("build", "--no-tgz"); Dist::Zilla::App->new->run }
system "git", "add", ".";
system "git", "clean", "-xfdq";

__DATA__

@@ Changes
Revision history for <%= $dist %>

{{$NEXT}}
  - Initial version

@@ t/00_use.t
use v5.24;
use warnings;
use experimental qw(lexical_subs signatures);

use Test::More tests => 1;
use <%= $module %>;
pass "happy hacking!";

@@ Build.PL
use v5.24;
use warnings;
use experimental qw(lexical_subs signatures);

use Module::Build::Tiny;
Build_PL;

@@ .gitattributes
.gitattributes export-ignore
.gitignore export-ignore
.github/ export-ignore
README.md export-ignore
author/ export-ignore
dist.pl export-ignore
eg/ export-ignore
example/ export-ignore
maint/ export-ignore
xt/ export-ignore

@@ .gitignore
/<%= $dist %>-*
/.build/

@@ .github/workflows/ci.yml
name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.24.4'
          - 'latest'
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        run: |
          curl -fsSL https://github.com/skaji/cpm-test/releases/download/0.01/ubuntu-24.04-perl-${{ matrix.perl-version }}.tar.xz | tar xJf - -C /tmp
          echo /tmp/perl-${{ matrix.perl-version }}/bin >> $GITHUB_PATH
      - run: perl -V
      - name: Install Dependencies
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install -g --top-level-phase runtime,test,develop --top-level-relationship requires,recommends --show-build-log-on-failure
      - run: prove -lr t
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: /usr/bin/perl -V
      - name: Install Dependencies
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | sudo -H /usr/bin/perl - install -g --top-level-phase runtime,test,develop --top-level-relationship requires,recommends --show-build-log-on-failure
      - run: /usr/bin/prove -lr t
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - run: perl -V
      - name: Install Dependencies
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install -g --top-level-phase runtime,test,develop --top-level-relationship requires,recommends --show-build-log-on-failure
      - run: prove -lr t

  release:
    needs:
      - test-linux
      - test-macos
      - test-windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # actions/attest
      attestations: write # actions/attest
      artifact-metadata: write # actions/attest
      contents: write # gh release
    steps:
      - uses: actions/checkout@v6
      - name: Prepare variables
        id: var
        run: echo dist=$(jq -r '"\(.name)-\(.version)\(if .release_status == "stable" then "" else "-TRIAL" end)"' META.json) >> $GITHUB_OUTPUT
      - name: Generate tarball
        run: |
          git archive --format=tar \
            --prefix=${{ steps.var.outputs.dist }}/ \
            'HEAD^{tree}' | gzip -n -9 > ${{ steps.var.outputs.dist }}.tar.gz
      - uses: actions/attest@v4
        id: attest
        with:
          subject-path: ${{ steps.var.outputs.dist }}.tar.gz
      - name: Create release
        run: |
          gh release create --repo ${{ github.repository }} ${{ github.ref_name }} \
            --notes "Artifact attestation: ${{ steps.attest.outputs.attestation-url }}" \
            ${{ steps.var.outputs.dist }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: skaji/action-pause-upload@v1
        with:
          files: ${{ steps.var.outputs.dist }}.tar.gz
          pause-token: ${{ secrets.PAUSE_TOKEN }}

@@ dist.pl
use v5.42;

package Trial {
    use Moose;
    with 'Dist::Zilla::Role::FileMunger';
    sub munge_file ($self, $file) {
        return if !($ENV{DZIL_RELEASING} && $file->name eq $self->zilla->main_module->name);
        my @line;
        for my $line (split /\n/, $file->content, -1) {
            if ($line =~ /^our \$TRIAL/) {
                my $trial_line = sprintf 'our $TRIAL = %d;', $self->zilla->is_trial ? 1 : 0;
                push @line, $trial_line;
            } else {
                push @line, $line;
            }
        }
        $file->content(join "\n", @line);
    }
}

package VersionFromMainModule {
    use Moose;
    with 'Dist::Zilla::Role::VersionProvider', 'Dist::Zilla::Role::ModuleMetadata';
    sub provide_version ($self, @) {
        my $metadata = $self->module_metadata_for_file($self->zilla->main_module, collect_pod => 0);
        my $version = $metadata->version;
        "$version";
    }
}

package NextRelease {
    use Moose;
    extends 'Dist::Zilla::Plugin::NextRelease';
    sub after_release ($self, @) {} # noop
}

my @prereq = (
    [ Prereqs => 'ConfigureRequires' ] => [
        'Module::Build::Tiny' => '0.053',
    ],
    [ Prereqs => 'RuntimeRequires' ] => [
        'perl' => 'v5.24',
    ],
);

my @plugin = (
    'ExecDir' => [ dir => 'script' ],
    'Git::GatherDir' => [ exclude_filename => 'META.json' ],
    'CopyFilesFromBuild' => [ copy => 'META.json' ],
    '=VersionFromMainModule' => [],
    'ReversionOnRelease' => [],
    '=NextRelease' => [ format => '%v  %{yyyy-MM-dd HH:mm:ss VVV}d%{ (TRIAL RELEASE)}T' ],
    '=Trial' => [],
    'Git::Check' => [ allow_dirty => 'Changes', allow_dirty => 'META.json' ],
    'GithubMeta' => [ issues => 1 ],
    'ReadmeAnyFromPod' => [ type => 'markdown', filename => 'README.md', location => 'root' ],
    'MetaProvides::Package' => [ inherit_version => 0, inherit_missing => 0 ],
    'MetaJSON' => [],
    'Metadata' => [ x_static_install => 1 ],
    'Git::Contributors' => [],

    'CheckChangesHasContent' => [],
    'FakeRelease' => [],
    'CopyFilesFromRelease' => [ filename => 'Changes', match => '\.pm$' ],
    'Git::Commit' => [ commit_msg => '%v%t', allow_dirty => 'Changes', allow_dirty => 'META.json', allow_dirty_match => '\.pm$' ],
    'Git::Tag' => [ tag_format => '%v%t', tag_message => '%v%t' ],
    'Git::Push' => [],
);

my @config = (
    name => '<%= $dist %>',
    [ @prereq, @plugin ],
);

@@ Module.pm
package <%= $module %> v0.0.1;
use v5.24;
use warnings;
use experimental qw(lexical_subs signatures);

1;
<%# %>__END__

=encoding utf-8

=head1 NAME

<%= $module %> - blah blah blah

=head1 SYNOPSIS

  use <%= $module %>;

=head1 DESCRIPTION

<%= $module %> is

=head1 ARTIFACT ATTESTATIONS

GitHub Artifact Attestations are generated for release tarballs uploaded to
CPAN. If you care about provenance for the uploaded tarballs, see:

L<https://github.com/skaji/perl-<%= $dist %>/attestations>

=head1 COPYRIGHT AND LICENSE

Copyright <%= $year %> <%= $author %> <<%= $email %>>

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
